### ISSUE TITLE
Bug in ncov-watch.py

### ISSUE THREAD

**Issue by EricFournier3** [jts/ncov-random-scripts#2]
should replace 
files = find_files("*.pass.vcf.gz")
by 
files = find_files("*.pass.vcf")
in def get_from_directory()

it doesn't works with .gz files
I got the following error;
----------------------------------------------------------------------------------------------------
 File "pysam/libcbcf.pyx", line 4036, in pysam.libcbcf.VariantFile.__init__
  File "pysam/libcbcf.pyx", line 4299, in pysam.libcbcf.VariantFile.open
  File "pysam/libchtslib.pyx", line 516, in pysam.libchtslib.HTSFile.tell
NotImplementedError: seek not implemented in files compressed by method 1
-----------------------------------------------------------------------------------------------------
Thanks
Eric

**Comment by jts** [comment]
Hi @EricFournier3,

I've just expanded the search to also look for `.pass.vcf`. It works for me on gzipped compressed files from the ARTIC bioinformatics pipeline, can you attach an example file where it fails for you?

Jared

**Comment by jts** [comment]
Based on [this](https://github.com/pysam-developers/pysam/issues/536), the compression error seems to be that pysam can't handle gzipped files, only bgzip. I'm unable to fix this so you'll have to unzip first, unfortunately

**Comment by EricFournier3** [comment]
Hi Jared,

It would also be useful to save the output in a file (add -o argument) and let the user decide if only pass vcf is to be analysed

Thanks

**Comment by jts** [comment]
For the second one I suggest you use the standard input mode so you can apply custom filtering to the input:

```
find data -name *.vcf | grep pass.vcf  | python ncov-watch.py [...]
```

I can add an `-o` option as well but it would be the same as redirecting stdout to a file?

Jared

**Comment by EricFournier3** [comment]
yes, the redirection and using the standard input is good as well

Thanks for your time

Eric

**Comment by EricFournier3** [comment]
Thanks Jared
